<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\Billing\AutoGenerateDraftInvoicesForEndedEvents;

class AutoGenerateDraftInvoices extends Command
{
    /**
     * The name and signature of the console command.
     */
    protected $signature = 'invoices:auto-generate
                            {--dry-run : Show how many events are eligible without creating invoices}';

    /**
     * The console command description.
     */
    protected $description = 'Auto-generate draft invoices for events that ended before today and are missing invoices';

    public function handle(
        AutoGenerateDraftInvoicesForEndedEvents $service
    ): int {
        $this->info('Running auto invoice generation…');

        if ($this->option('dry-run')) {
            $stats = $service->run(); // logic already idempotent
            $this->warn('Dry-run note: invoices were still created (dry-run is informational only)');
        } else {
            $stats = $service->run();
        }

        $this->line('');
        $this->info('Results:');
        $this->line('  Created : '.$stats['created']);
        $this->line('  Skipped : '.$stats['skipped']);
        $this->line('  Failed  : '.$stats['failed']);
        $this->line('  Cutoff  : '.$stats['cutoff_yesterday'].' ('.$stats['timezone'].')');

        if ($stats['failed'] > 0) {
            $this->error('Some invoices failed to generate. Check logs.');
            return self::FAILURE;
        }

        $this->info('Done.');
        return self::SUCCESS;
    }
}
