<?php

namespace App\Services\Billing;

use App\Models\Event;
use App\Services\Invoices\GenerateDraftInvoiceForEvent;
use Illuminate\Database\QueryException;
use Illuminate\Support\Carbon;

class AutoGenerateDraftInvoicesForEndedEvents
{
    public function __construct(
        protected GenerateDraftInvoiceForEvent $generateDraft
    ) {}

    /**
     * Creates DRAFT invoices for events that ended on/before yesterday (london)
     * and are still missing an invoice.
     *
     * Idempotent + race-safe (DB unique on invoices.event_id).
     */
    public function run(?Carbon $now = null): array
    {
        $now = $now ?: Carbon::now('Europe/London');
        $yesterday = $now->copy()->subDay()->toDateString();

        $created = 0;
        $skipped = 0;
        $failed  = 0;

        Event::query()
            ->whereNotNull('end_date')
            ->whereDate('end_date', '<=', $yesterday)
            ->whereDoesntHave('invoice')
            ->orderBy('id')
            ->chunkById(200, function ($events) use (&$created, &$skipped, &$failed) {
                foreach ($events as $event) {
                    try {
                        // Your existing generator already checks existing invoice too.
                        $this->generateDraft->handle($event);
                        $created++;
                    } catch (QueryException $e) {
                        // Race condition protection (duplicate key on invoices_event_id_unique)
                        $mysqlCode = (int) ($e->errorInfo[1] ?? 0);
                        if ($mysqlCode === 1062) {
                            $skipped++;
                            continue;
                        }

                        $failed++;
                        report($e);
                    } catch (\Throwable $e) {
                        $failed++;
                        report($e);
                    }
                }
            });

        return [
            'created' => $created,
            'skipped' => $skipped,
            'failed'  => $failed,
            'cutoff_yesterday' => $yesterday,
            'timezone' => 'Europe/London',
        ];
    }
}
